### ISSUE TITLE
Problem loading pretrained weights: Missing keys: downsample layers

### ISSUE THREAD

**Issue by BarakBat** [kenshohara/3D-ResNets-PyTorch#110] opened 2018-10-20 14:25 UTC
Hi I'm getting this error when trying to load weights to resnet34 model:

> RuntimeError: Error(s) in loading state_dict for ResNet:
>         Missing key(s) in state_dict: "layer2.0.downsample.0.weight", "layer2.0.downsample.1.weight", "layer2.0.downsample.1.bias", "layer2.0.downsample.1.running_mean", "layer2.0.downsample.1.running_var", "layer3.0.downsample.0.weight", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.bias", "layer3.0.downsample.1.running_mean", "layer3.0.downsample.1.running_var", "layer4.0.downsample.0.weight", "layer4.0.downsample.1.weight", "layer4.0.downsample.1.bias", "layer4.0.downsample.1.running_mean", "layer4.0.downsample.1.running_var".

It's all the downsample layers, someone has any Idea what I did wrong??

**Comment by ZelongZeng** [comment] 2018-10-23 05:01
Yeah, I met same problem, load the pretrained model(resnet-152) and the size is wrong

**Comment by ZelongZeng** [comment] 2018-10-23 06:34
the resnet152 has 932 layers totally, but the pretrained model only has 777 layers, I am not sure if I made any mistake?

**Comment by tomrunia** [comment] 2018-11-12 16:15
Same problem here when trying to finetune ResNet-18. 

```
Traceback (most recent call last):
  File "finetune.py", line 181, in <module>
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/-/dev/virtualenv/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.layer2.0.downsample.0.weight", "module.layer2.0.downsample.1.weight", "module.layer2.0.downsample.1.bias", "module.layer2.0.downsample.1.running_mean", "module.layer2.0.downsample.1.running_var", "module.layer3.0.downsample.0.weight", "module.layer3.0.downsample.1.weight", "module.layer3.0.downsample.1.bias", "module.layer3.0.downsample.1.running_mean", "module.layer3.0.downsample.1.running_var", "module.layer4.0.downsample.0.weight", "module.layer4.0.downsample.1.weight", "module.layer4.0.downsample.1.bias", "module.layer4.0.downsample.1.running_mean", "module.layer4.0.downsample.1.running_var".
```

**Comment by tomrunia** [comment] 2018-11-13 16:46
Already found the solution, the problem is fixed by setting the different ResNet shortcut with `--resnet_shortcut='A'`

**Comment by JoshuaC3** [comment] 2019-01-11 15:52
For those that wish to load this into memory/GPU them selves:

```
model = resnet34(sample_size=16, sample_duration=4, shortcut_type='A')
model = DataParallel(model, device_ids=None)

pretrained_weights = torch.load('../models/resnet-34-kinetics.pth')
model.load_state_dict(pretrained_weights['state_dict'])
```

**Closed** 2019-02-16 11:44 UTC

**Comment by BibratRanjan** [comment] 2019-03-15 05:10
I faced similar issue while loading kinetics pretrained weights for resnet-101 and resnext-101. Solution was changing the shortcut connection type from A to B
